<?php
define('CLE_HELPER_GROUP_BUNDLE', 'section');
/**
 * @file
 * Code for the CLE distribution.
 */

/**
 * Implements hook_init().
 */
function cle_helper_init() {
  // placeholder during debug
  drupal_add_css(drupal_get_path('module', 'cle_helper') . '/cle_helper.css');
}

/**
 * Implements hook_lti_tool_provider_launch_alter().
 */
function cle_helper_lti_tool_provider_launch_alter(&$launch_info, $account) {
}